export const GET_POSTS_START = "GET_POSTS_START";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const INITIATE_PAGES = "INITIATE_PAGES";

export const DELETE_POSTS_START = "DELETE_POSTS_START";
export const DELETE_POSTS_FAILURE = "DELETE_POSTS_FAILURE";
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";

export const GET_POST_START = "GET_POST_START";
export const GET_POST_FAILURE = "GET_POST_FAILURE";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const EDIT_POSTS_START = "EDIT_POSTS_START";
export const EDIT_POSTS_FAILURE = "EDIT_POSTS_FAILURE";
export const EDIT_POSTS_SUCCESS = "EDIT_POSTS_SUCCESS";
